package ru.bash.syntax.token

enum class TokenType {
    WORD,
    PIPELINE,
    VAR,
    EXIT_STATUS,
    COMMAND_SUBSTITUTION,
    ARITHMETIC_EXPANSION,
    SINGLE_QUOTED,
    DOUBLE_QUOTED_LITERAL,
    REDIRECT_IN,
    REDIRECT_OUT,
    REDIRECT_APPEND,
    EOF
}
